// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Data;

#nullable disable

namespace Restaurant.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260508110032_addedSeedData")]
    partial class addedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingTable", b =>
                {
                    b.Property<int>("BookingsId")
                        .HasColumnType("int");

                    b.Property<int>("TablesId")
                        .HasColumnType("int");

                    b.HasKey("BookingsId", "TablesId");

                    b.HasIndex("TablesId");

                    b.ToTable("BookingTables", (string)null);

                    b.HasData(
                        new
                        {
                            BookingsId = 1,
                            TablesId = 8
                        },
                        new
                        {
                            BookingsId = 2,
                            TablesId = 1
                        },
                        new
                        {
                            BookingsId = 3,
                            TablesId = 2
                        },
                        new
                        {
                            BookingsId = 3,
                            TablesId = 9
                        });
                });

            modelBuilder.Entity("Restaurant.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Restaurant.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("BookingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateBooked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfGuests = 2,
                            BookingNotes = "Jubileum — gärna levande ljus",
                            DateBooked = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2025, 5, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            StartTime = new DateTime(2025, 5, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AmountOfGuests = 4,
                            DateBooked = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2025, 5, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 2,
                            StartTime = new DateTime(2025, 5, 11, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AmountOfGuests = 6,
                            BookingNotes = "Allergiker i sällskapet",
                            DateBooked = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2025, 5, 12, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 3,
                            StartTime = new DateTime(2025, 5, 12, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Restaurant.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEighteen")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allergies = "Gluten",
                            Email = "anna.lindqvist@email.se",
                            FirstName = "Anna",
                            IsEighteen = true,
                            LastName = "Lindqvist",
                            Note = "Föredrar fönsterbord",
                            Password = "password123",
                            PhoneNumber = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "erik.svensson@email.se",
                            FirstName = "Erik",
                            IsEighteen = true,
                            LastName = "Svensson",
                            Password = "password123",
                            PhoneNumber = "0709876543"
                        },
                        new
                        {
                            Id = 3,
                            Allergies = "Nötter, Laktos",
                            Email = "maria.johansson@email.se",
                            FirstName = "Maria",
                            IsEighteen = false,
                            LastName = "Johansson",
                            Note = "Allergiker — dubbelkolla alltid",
                            Password = "password123",
                            PhoneNumber = "0731122334"
                        });
                });

            modelBuilder.Entity("Restaurant.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableNumber")
                        .IsUnique();

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Seats = 4,
                            TableNumber = 10
                        },
                        new
                        {
                            Id = 2,
                            Seats = 4,
                            TableNumber = 20
                        },
                        new
                        {
                            Id = 3,
                            Seats = 4,
                            TableNumber = 30
                        },
                        new
                        {
                            Id = 4,
                            Seats = 4,
                            TableNumber = 40
                        },
                        new
                        {
                            Id = 5,
                            Seats = 4,
                            TableNumber = 50
                        },
                        new
                        {
                            Id = 6,
                            Seats = 4,
                            TableNumber = 60
                        },
                        new
                        {
                            Id = 7,
                            Seats = 4,
                            TableNumber = 70
                        },
                        new
                        {
                            Id = 8,
                            Seats = 2,
                            TableNumber = 15
                        },
                        new
                        {
                            Id = 9,
                            Seats = 2,
                            TableNumber = 25
                        },
                        new
                        {
                            Id = 10,
                            Seats = 2,
                            TableNumber = 35
                        },
                        new
                        {
                            Id = 11,
                            Seats = 2,
                            TableNumber = 45
                        },
                        new
                        {
                            Id = 12,
                            Seats = 2,
                            TableNumber = 55
                        },
                        new
                        {
                            Id = 13,
                            Seats = 2,
                            TableNumber = 65
                        },
                        new
                        {
                            Id = 14,
                            Seats = 2,
                            TableNumber = 75
                        });
                });

            modelBuilder.Entity("BookingTable", b =>
                {
                    b.HasOne("Restaurant.Models.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Models.Table", null)
                        .WithMany()
                        .HasForeignKey("TablesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Models.Booking", b =>
                {
                    b.HasOne("Restaurant.Models.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Restaurant.Models.Guest", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
