// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.API.Data;

#nullable disable

namespace REST_aurant.API.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260512123105_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingTable", b =>
                {
                    b.Property<int>("BookingsId")
                        .HasColumnType("int");

                    b.Property<int>("TablesTableNumber")
                        .HasColumnType("int");

                    b.HasKey("BookingsId", "TablesTableNumber");

                    b.HasIndex("TablesTableNumber");

                    b.ToTable("BookingTables", (string)null);

                    b.HasData(
                        new
                        {
                            BookingsId = 1,
                            TablesTableNumber = 1
                        },
                        new
                        {
                            BookingsId = 3,
                            TablesTableNumber = 5
                        },
                        new
                        {
                            BookingsId = 3,
                            TablesTableNumber = 6
                        });
                });

            modelBuilder.Entity("Restaurant.Models.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("BookingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateBooked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfGuests = 2,
                            BookingNotes = "Dejt-kväll",
                            DateBooked = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2026, 5, 8, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            StartTime = new DateTime(2026, 5, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AmountOfGuests = 4,
                            BookingNotes = "Inställt pga sjukdom",
                            DateBooked = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2026, 5, 10, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 2,
                            StartTime = new DateTime(2026, 5, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AmountOfGuests = 12,
                            BookingNotes = "Släktträff",
                            DateBooked = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2026, 5, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 3,
                            StartTime = new DateTime(2026, 5, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Restaurant.Models.Models.Table", b =>
                {
                    b.Property<int>("TableNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableNumber"));

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("TableNumber");

                    b.HasIndex("TableNumber")
                        .IsUnique();

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableNumber = 1,
                            Seats = 2
                        },
                        new
                        {
                            TableNumber = 2,
                            Seats = 2
                        },
                        new
                        {
                            TableNumber = 3,
                            Seats = 4
                        },
                        new
                        {
                            TableNumber = 4,
                            Seats = 4
                        },
                        new
                        {
                            TableNumber = 5,
                            Seats = 6
                        },
                        new
                        {
                            TableNumber = 6,
                            Seats = 10
                        });
                });

            modelBuilder.Entity("Restaurant.Models.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Restaurant.Models.Models.Admin", b =>
                {
                    b.HasBaseType("Restaurant.Models.Models.User");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Email = "admin@mail.com",
                            Password = "Admin123"
                        });
                });

            modelBuilder.Entity("Restaurant.Models.Models.Guest", b =>
                {
                    b.HasBaseType("Restaurant.Models.Models.User");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Guest");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Email = "erik@mail.com",
                            Password = "Lösen123",
                            FirstName = "Erik",
                            LastName = "Eriksson",
                            Note = "Fyller år!",
                            PhoneNumber = "070-4445566"
                        },
                        new
                        {
                            Id = 3,
                            Email = "stig@mail.com",
                            Password = "Lösen123",
                            Allergies = "Laktos",
                            FirstName = "Stig",
                            LastName = "Stigsson",
                            Note = "Barnstol behövs",
                            PhoneNumber = "070-7778899"
                        },
                        new
                        {
                            Id = 1,
                            Email = "anna@mail.com",
                            Password = "Lösen123",
                            Allergies = "Nötter",
                            FirstName = "Anna",
                            LastName = "Andersson",
                            Note = "Vill sitta vid fönstret",
                            PhoneNumber = "070-1112233"
                        });
                });

            modelBuilder.Entity("BookingTable", b =>
                {
                    b.HasOne("Restaurant.Models.Models.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Models.Models.Table", null)
                        .WithMany()
                        .HasForeignKey("TablesTableNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.Models.Models.Booking", b =>
                {
                    b.HasOne("Restaurant.Models.Models.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Restaurant.Models.Models.Guest", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
